// Code generated by MockGen. DO NOT EDIT.
// Source: todo_logic.go
//
// Generated by this command:
//
//	mockgen -package logic -source todo_logic.go -destination mock_todo_logic.go
//
// Package logic is a generated GoMock package.
package logic

import (
	reflect "reflect"

	models "github.com/tasuke/go-mux-task/models"
	gomock "go.uber.org/mock/gomock"
)

// MockITodoLogic is a mock of ITodoLogic interface.
type MockITodoLogic struct {
	ctrl     *gomock.Controller
	recorder *MockITodoLogicMockRecorder
}

// MockITodoLogicMockRecorder is the mock recorder for MockITodoLogic.
type MockITodoLogicMockRecorder struct {
	mock *MockITodoLogic
}

// NewMockITodoLogic creates a new mock instance.
func NewMockITodoLogic(ctrl *gomock.Controller) *MockITodoLogic {
	mock := &MockITodoLogic{ctrl: ctrl}
	mock.recorder = &MockITodoLogicMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITodoLogic) EXPECT() *MockITodoLogicMockRecorder {
	return m.recorder
}

// CreateAllTodoResponse mocks base method.
func (m *MockITodoLogic) CreateAllTodoResponse(todos *[]models.Todo) []models.BaseTodoResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAllTodoResponse", todos)
	ret0, _ := ret[0].([]models.BaseTodoResponse)
	return ret0
}

// CreateAllTodoResponse indicates an expected call of CreateAllTodoResponse.
func (mr *MockITodoLogicMockRecorder) CreateAllTodoResponse(todos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAllTodoResponse", reflect.TypeOf((*MockITodoLogic)(nil).CreateAllTodoResponse), todos)
}

// CreateTodoResponse mocks base method.
func (m *MockITodoLogic) CreateTodoResponse(todo *models.Todo) models.BaseTodoResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTodoResponse", todo)
	ret0, _ := ret[0].(models.BaseTodoResponse)
	return ret0
}

// CreateTodoResponse indicates an expected call of CreateTodoResponse.
func (mr *MockITodoLogicMockRecorder) CreateTodoResponse(todo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTodoResponse", reflect.TypeOf((*MockITodoLogic)(nil).CreateTodoResponse), todo)
}
